# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Xliff2Strings' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Xliff2Strings

  pod 'ReactiveObjC'

  target 'Xliff2StringsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Xliff2StringsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
